### ISSUE TITLE
Form::password arguments are misinterpreted in VM

### ISSUE THREAD

**Issue by ThomDietrich** [ILSCeV/Lara#210]
On a fresh setup (`[develop]v2.1.2-1167(a943ead)`) with the provided seeds migrated I'm seeing the following error when clicking "Neue Umfrage":

![2016-12-08 11_26_49-pale moon](https://cloud.githubusercontent.com/assets/2870104/21006448/43e96cdc-bd39-11e6-9d5a-ae8491ed9a33.png)

With the current efforts to implement lara in all sections, interested developers should be able to get a working system running quickly ;) I've updated homestead-lara-vedst to be functional once more for an interested BH-Club member. After the described error is sorted out he wants to have a look around lara.

**Comment by ThomDietrich** [comment]
"Neues Event:"

![2016-12-08 11_34_33-pale moon](https://cloud.githubusercontent.com/assets/2870104/21006700/5ce76a26-bd3a-11e6-9b25-5428544d8d4b.png)

**Comment by 4D44H** [comment]
It seems that this has nothing to do with the seeds, i just created a new DB, ran "php artisan migrate:refresh && composer dump-autoload && php artisan db:seed" and could not reproduce the error - everything loads and works fine.
![image](https://cloud.githubusercontent.com/assets/11014468/21029042/2b8094b8-bd98-11e6-85ae-143f46a179ca.png)

Check that you aren't using an old cached view.
-> Please run "composer update" (intead of "install", maybe the lock-file is outdated) followed by "composer dump-autoload" and see if the problem is still there.
 
On a side-note:
iSeed was never used outside of the survey software project team, and was not changed since. 
We are working with a production DB dump to be able to test on real data.
-> I added a ticket for the seeds update to the queue, but if you need it fast, you can have a look at it yourself. 

If you have a person who is interested, he/she might as well contact me directly.

**Comment by 4D44H** [comment]
Also, there are 3 errors in first screenshot and 2 in the second - are all of them the same errors? If not, please provide them as well.

**Comment by ThomDietrich** [comment]
![2016-12-09 12_52_54-pale moon](https://cloud.githubusercontent.com/assets/2870104/21048224/7030820a-be0e-11e6-851b-fc4314f88c0f.png)

![2016-12-09 12_52_44-pale moon](https://cloud.githubusercontent.com/assets/2870104/21048223/702f0b3c-be0e-11e6-95c1-a8b86fc0aa73.png)


![2016-12-09 12_52_29-pale moon](https://cloud.githubusercontent.com/assets/2870104/21048222/700df730-be0e-11e6-9823-c1cb3135dfc7.png)

**Comment by ThomDietrich** [comment]
I do not know if the error is related to the seeds or the migration.
homestead-lara-vedst does [the following](https://github.com/ILSCeV/homestead-lara-vedst/blob/master/src/stubs/after.sh#L47-L57):

```
composer install --no-progress
php artisan migrate --seed
php artisan key:generate
```
The last time I checked this is all that's needed to get the environment ready and to create and populate the database.

> Check that you aren't using an old cached view.

I'm in homestead. That's as old-cache-less as it gets ;)

> iSeed

That's okay, it's only used to create the seed. If the DB schema changed since the last creating, that would be a problem...

**Comment by ThomDietrich** [comment]
> Please run "composer update" (intead of "install", maybe the lock-file is outdated) followed by "composer dump-autoload" and see if the problem is still there.

Didn't help. I don't see the benefit. One should not update the lock file lightly as far as I remember...

I have just deleted the seeded data by re-running just the migration. Still the same error

**Comment by 4D44H** [comment]
The error has nothing to do with the database.
It is thrown by the LaravelCollective FormHelper (https://github.com/LaravelCollective/html), which should be in version 5.3.* in composer.
I have no idea why it's only seen in your VM and is rendered correctly otherwise.

Let's try to isolate it - are only password inputs the problem?
- Please remove lines 306 to 318 in resources/views/createClubEventView.blade.php and try pressing "create new event".
- remove lines 56 to 79 in resources/views/partials/surveyForm.blade.php and try pressing "create new survey".

Are both pages now loading without errors, with no inputs for passwords?

**Comment by ThomDietrich** [comment]
Solved.
Following [this thread](http://laravel.io/forum/08-12-2014-illegal-string-offset-name-when-validating-against-unique) I removed "`, ''`" from the four `Form::password()` calls.
I will not create a PR. I think it's better you take a deeper look into why this works for you but doesn't for me. ;)

**Comment by 4D44H** [comment]
> Which editor(s) are you guys using by the way? 
PHPStorm and Sublime

> Following this thread...
I've also seen it, but it's not exactly the same issue - they are seeing the same error message, but because of a different cause - the "Input::old('password')" clause, which was deprecated in Laravel 5.1 or 5.2 I think. We didn't have it in our code.

I'll look closer at this issue a bit later and make sure removing arguments has no side-effects on other parts of the code. Thanks for reporting, good job!

**Comment by 4D44H** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[1] Events and Surveys: check that Form::password get proper arguments](https://trello.com/c/biL4cCvr/94-1-events-and-surveys-check-that-form-password-get-proper-arguments)

**Comment by ThomDietrich** [comment]
Great. Will you still commit the changes? Would be nice to have a working VM again... ;)

Regarding the editor: It would probably be a good idea to clean up this mess. Yes it will take some time, yes it will destroy your git blame history.

**Comment by 4D44H** [comment]
Commit - yes, when it's ready.

Cleanup - yes, a bit later.

**Comment by ThomDietrich** [comment]
Confirmed working again. :+1:
